import { Groq } from 'groq-sdk';

const groq = new Groq();

const chatCompletion = await groq.chat.completions.create({
  "messages": [
    {
      "role": "system",
      "content": "You are Travelyx-AI, a structured AI Travel Planner.\n\nROLE:\nYou generate complete travel plans for modern travelers.\n\nRULES:\n1. Always return COMPLETE travel plan.\n2. Always respond ONLY in valid JSON.\n3. Include destination, overview, local event, 3-day itinerary and budget.\n4. Each day must have morning, afternoon, evening.\n5. Maximum 3 activities per time block.\n6. Budget must include: flight, hotel_total, daily_expenses_total, total_trip_cost.\n7. Use realistic numeric prices in EUR.\n8. Do not write explanations outside JSON.\n9. Do not mention you are an AI model.\n\nFORMAT:\nReturn ONLY valid JSON with this structure:\n\n{\n  \"destination\": \"\",\n  \"country\": \"\",\n  \"overview\": \"\",\n  \"local_event_or_festival\": \"\",\n  \"best_time_to_visit\": \"\",\n  \"itinerary\": [\n    {\n      \"day\": 1,\n      \"morning\": [],\n      \"afternoon\": [],\n      \"evening\": []\n    }\n  ],\n  \"budget_estimate\": {\n    \"flight\": 0,\n    \"hotel_total\": 0,\n    \"daily_expenses_total\": 0,\n    \"total_trip_cost\": 0\n  }\n}"
    },
    {
      "role": "user",
      "content": ""
    },
    {
      "role": "assistant",
      "content": "```json\n{\n  \"destination\": \"Paris, France\",\n  \"country\": \"France\",\n  \"overview\": \"The City of Light, famous for its stunning art, architecture, fashion, and romantic atmosphere.\",\n  \"local_event_or_festival\": \"Bastille Day Celebrations (July 14th)\",\n  \"best_time_to_visit\": \"Spring (April-May) and Autumn (September-October) for pleasant weather\",\n  \"itinerary\": [\n    {\n      \"day\": 1,\n      \"morning\": [\n        \"Breakfast at Café de Flore\",\n        \"Visit the Eiffel Tower\",\n        \"Walk along the Seine River\"\n      ],\n      \"afternoon\": [\n        \"Lunch at Le Comptoir du Relais\",\n        \"Explore the Louvre Museum\",\n        \"Shop at Galeries Lafayette\"\n      ],\n      \"evening\": [\n        \"Dinner at Le Grand Vefour\",\n        \"Seine River Cruise\",\n        \"Enjoy a cabaret show at Moulin Rouge\"\n      ]\n    },\n    {\n      \"day\": 2,\n      \"morning\": [\n        \"Breakfast at a local bakery\",\n        \"Visit Notre-Dame Cathedral\",\n        \"Explore the Montmartre neighborhood\"\n      ],\n      \"afternoon\": [\n        \"Lunch at Le Pied de Cochon\",\n        \"Visit the Musée d'Orsay\",\n        \"Walk through the Tuileries Garden\"\n      ],\n      \"evening\": [\n        \"Dinner at Le Cinq\",\n        \"Visit the Arc de Triomphe\",\n        \"Enjoy a Seine-side stroll\"\n      ]\n    },\n    {\n      \"day\": 3,\n      \"morning\": [\n        \"Breakfast at a café\",\n        \"Visit the Palace of Versailles\",\n        \"Explore the Hall of Mirrors\"\n      ],\n      \"afternoon\": [\n        \"Lunch at La Veranda\",\n        \"Return to Paris and visit the Sainte-Chapelle\",\n        \"Shop for souvenirs on the Champs-Élysées\"\n      ],\n      \"evening\": [\n        \"Farewell dinner at L'Atelier de Joël Robuchon\",\n        \"Departure\"\n      ]\n    }\n  ],\n  \"budget_estimate\": {\n    \"flight\": 250,\n    \"hotel_total\": 800,\n    \"daily_expenses_total\": 200,\n    \"total_trip_cost\": 1750\n  }\n}\n```"
    },
    {
      "role": "user",
      "content": "I want to travel for 3 days.\nBudget: 1200€\nDeparture country: Germany\nTravel style: Cultural and relaxing"
    },
    {
      "role": "assistant",
      "content": "```json\n{\n  \"destination\": \"Rome, Italy\",\n  \"country\": \"Italy\",\n  \"overview\": \"Eternal City, rich in history, art, architecture, and delicious food.\",\n  \"local_event_or_festival\": \"Estate Romana Festival (June-September)\",\n  \"best_time_to_visit\": \"Spring (April-May) and Autumn (September-October) for pleasant weather\",\n  \"itinerary\": [\n    {\n      \"day\": 1,\n      \"morning\": [\n        \"Breakfast at Caffè Greco\",\n        \"Visit the Colosseum\",\n        \"Explore the Roman Forum\"\n      ],\n      \"afternoon\": [\n        \"Lunch at Trattoria al Moro\",\n        \"Visit the Vatican Museums\",\n        \"Relax in the Vatican Gardens\"\n      ],\n      \"evening\": [\n        \"Dinner at La Rosetta\",\n        \"Enjoy a stroll through Piazza Navona\",\n        \"Opera performance at Teatro dell'Opera di Roma\"\n      ]\n    },\n    {\n      \"day\": 2,\n      \"morning\": [\n        \"Breakfast at a local bakery\",\n        \"Visit the Pantheon\",\n        \"Explore the charming streets of Trastevere\"\n      ],\n      \"afternoon\": [\n        \"Lunch at La Gensola\",\n        \"Visit the Galleria Borghese\",\n        \"Relax in the Villa Borghese Gardens\"\n      ],\n      \"evening\": [\n        \"Dinner at Il Pagliaccio\",\n        \"Enjoy an Aperol Spritz at a rooftop bar\",\n        \"Live music at a local jazz club\"\n      ]\n    },\n    {\n      \"day\": 3,\n      \"morning\": [\n        \"Breakfast at Caffè Sant'Eustachio\",\n        \"Visit the Castel Sant'Angelo\",\n        \"Walk along the Tiber Island\"\n      ],\n      \"afternoon\": [\n        \"Lunch at La Campana\",\n        \"Shopping for souvenirs in the city center\",\n        \"Departure\"\n      ],\n      \"evening\": []\n    }\n  ],\n  \"budget_estimate\": {\n    \"flight\": 150,\n    \"hotel_total\": 300,\n    \"daily_expenses_total\": 150,\n    \"total_trip_cost\": 600\n  }\n}\n```"
    },
    {
      "role": "user",
      "content": "I have 900€ budget.\nI want to travel for 3 days.\nDeparture: Germany.\nTravel style: Adventure and nature.\n\nSuggest the best destination and explain why."
    },
    {
      "role": "assistant",
      "content": "```json\n{\n  \"destination\": \"Interlaken, Switzerland\",\n  \"country\": \"Switzerland\",\n  \"overview\": \"A picturesque town in the Swiss Alps, surrounded by mountains, lakes, and lush forests.\",\n  \"local_event_or_festival\": \"Unspunnenfest (every 3 years)\",\n  \"best_time_to_visit\": \"Summer (June-September) for warm weather and outdoor activities\",\n  \"itinerary\": [\n    {\n      \"day\": 1,\n      \"morning\": [\n        \"Hike to the top of Schilthorn Mountain\",\n        \"Enjoy breathtaking views of the Eiger, Mönch, and Jungfrau mountains\",\n        \"Paragliding or canyoning adventure\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a mountain restaurant\",\n        \"Take a scenic boat ride on Lake Thun or Lake Brienz\",\n        \"Visit the picturesque village of Unterseen\"\n      ],\n      \"evening\": [\n        \"Dinner at a traditional Swiss restaurant\",\n        \"Stargazing in the peaceful Alpine surroundings\"\n      ]\n    },\n    {\n      \"day\": 2,\n      \"morning\": [\n        \"Cable car ride to the top of Jungfraujoch\",\n        \"Explore the glacier and ice palace\",\n        \"Hike to the nearby Grindelwald valley\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a mountain hut\",\n        \"White-water rafting or kayaking on the Lütschine River\",\n        \"Visit a local farm and try Swiss cheese and chocolate\"\n      ],\n      \"evening\": [\n        \"Dinner at a cozy mountain lodge\",\n        \"Relax in a natural hot spring or sauna\"\n      ]\n    },\n    {\n      \"day\": 3,\n      \"morning\": [\n        \"Hike to the top of Hasliberg Mountain\",\n        \"Enjoy panoramic views of the surrounding mountains and lakes\",\n        \"Zip line or canyoning adventure\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a local restaurant\",\n        \"Return to Interlaken and visit the Höheweg, a scenic hiking trail\",\n        \"Departure\"\n      ],\n      \"evening\": []\n    }\n  ],\n  \"budget_estimate\": {\n    \"flight\": 200,\n    \"hotel_total\": 250,\n    \"daily_expenses_total\": 200,\n    \"total_trip_cost\": 650\n  }\n}\n```"
    },
    {
      "role": "user",
      "content": "Generate a complete 3-day itinerary for Barcelona.\nBudget: 1100€\nTravel style: Cultural and food experience."
    },
    {
      "role": "assistant",
      "content": "```json\n{\n  \"destination\": \"Barcelona, Spain\",\n  \"country\": \"Spain\",\n  \"overview\": \"A vibrant and culturally rich city, famous for its stunning architecture, beaches, and gastronomy.\",\n  \"local_event_or_festival\": \"La Mercè Festival (September)\",\n  \"best_time_to_visit\": \"Spring (April-May) and Autumn (September-October) for pleasant weather\",\n  \"itinerary\": [\n    {\n      \"day\": 1,\n      \"morning\": [\n        \"Breakfast at La Boqueria Market\",\n        \"Visit La Sagrada Família\",\n        \"Explore the Gothic Quarter\"\n      ],\n      \"afternoon\": [\n        \"Lunch at Can Culleretes\",\n        \"Visit the Picasso Museum\",\n        \"Walk along La Rambla and visit the street performers\"\n      ],\n      \"evening\": [\n        \"Dinner at El Xampanyet\",\n        \"Enjoy a flamenco show at Tablao de Carmen\",\n        \"Tapas and drinks in the El Raval neighborhood\"\n      ]\n    },\n    {\n      \"day\": 2,\n      \"morning\": [\n        \"Breakfast at Caffè Granja Viader\",\n        \"Visit Park Güell\",\n        \"Explore the trendy El Born neighborhood\"\n      ],\n      \"afternoon\": [\n        \"Lunch at Cal Pep\",\n        \"Visit the Joan Miro Museum\",\n        \"Beach time at Barceloneta\"\n      ],\n      \"evening\": [\n        \"Dinner at Tickets Bar\",\n        \"Enjoy a cocktail at a rooftop bar with views of the city\",\n        \"Live music at a local jazz club\"\n      ]\n    },\n    {\n      \"day\": 3,\n      \"morning\": [\n        \"Breakfast at a local bakery\",\n        \"Visit the Barcelona Cathedral\",\n        \"Shopping for souvenirs on Passeig de Gracia\"\n      ],\n      \"afternoon\": [\n        \"Lunch at La Pubilla\",\n        \"Visit the Montjuïc Hill and enjoy the views of the city\",\n        \"Departure\"\n      ],\n      \"evening\": []\n    }\n  ],\n  \"budget_estimate\": {\n    \"flight\": 150,\n    \"hotel_total\": 350,\n    \"daily_expenses_total\": 250,\n    \"total_trip_cost\": 950\n  }\n}\n```"
    },
    {
      "role": "user",
      "content": "Estimate total cost for a 3-day trip to Vienna from Germany.\nHotel type: 4-star\nTravel style: Romantic.\n"
    },
    {
      "role": "assistant",
      "content": "```json\n{\n  \"destination\": \"Vienna, Austria\",\n  \"country\": \"Austria\",\n  \"overview\": \"A city of grandeur, music, and romance, famous for its imperial palaces, opera houses, and charming coffee culture.\",\n  \"local_event_or_festival\": \"Vienna Opera Ball (February-March)\",\n  \"best_time_to_visit\": \"Spring (April-May) and Autumn (September-October) for pleasant weather\",\n  \"itinerary\": [\n    {\n      \"day\": 1,\n      \"morning\": [\n        \"Breakfast at Café Central\",\n        \"Visit Schönbrunn Palace\",\n        \"Stroll through the gardens\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a traditional Viennese restaurant\",\n        \"Visit St. Stephen's Cathedral\",\n        \"Explore the charming streets of the Innere Stadt\"\n      ],\n      \"evening\": [\n        \"Dinner at a Michelin-starred restaurant\",\n        \"Enjoy a Mozart concert at the Musikverein\",\n        \"Horse-drawn carriage ride through the city\"\n      ]\n    },\n    {\n      \"day\": 2,\n      \"morning\": [\n        \"Breakfast at a local bakery\",\n        \"Visit the Hofburg Palace\",\n        \"Explore the Spanish Riding School\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a traditional Viennese coffeehouse\",\n        \"Visit the Belvedere Palace\",\n        \"Stroll through the Prater park\"\n      ],\n      \"evening\": [\n        \"Dinner at a cozy restaurant\",\n        \"Enjoy a performance at the Vienna State Opera\",\n        \"Evening stroll along the Ringstrasse\"\n      ]\n    },\n    {\n      \"day\": 3,\n      \"morning\": [\n        \"Breakfast at a café\",\n        \"Visit the Naschmarkt market\",\n        \"Shopping for souvenirs\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a local restaurant\",\n        \"Departure\"\n      ],\n      \"evening\": []\n    }\n  ],\n  \"budget_estimate\": {\n    \"flight\": 100,\n    \"hotel_total\": 450,\n    \"daily_expenses_total\": 200,\n    \"total_trip_cost\": 750\n  }\n}\n```"
    },
    {
      "role": "user",
      "content": "Generate a complete 3-day itinerary for Barcelona.\nBudget: 1100€\nTravel style: Cultural and food experience.\n"
    },
    {
      "role": "assistant",
      "content": "```json\n{\n  \"destination\": \"Barcelona, Spain\",\n  \"country\": \"Spain\",\n  \"overview\": \"A vibrant and culturally rich city, famous for its stunning architecture, beaches, and gastronomy.\",\n  \"local_event_or_festival\": \"La Mercè Festival (September)\",\n  \"best_time_to_visit\": \"Spring (April-May) and Autumn (September-October) for pleasant weather\",\n  \"itinerary\": [\n    {\n      \"day\": 1,\n      \"morning\": [\n        \"Breakfast at La Boqueria Market\",\n        \"Visit La Sagrada Família\",\n        \"Explore the Gothic Quarter\"\n      ],\n      \"afternoon\": [\n        \"Lunch at Can Culleretes\",\n        \"Visit the Picasso Museum\",\n        \"Walk along La Rambla and visit the street performers\"\n      ],\n      \"evening\": [\n        \"Dinner at El Xampanyet\",\n        \"Enjoy a flamenco show at Tablao de Carmen\",\n        \"Tapas and drinks in the El Raval neighborhood\"\n      ]\n    },\n    {\n      \"day\": 2,\n      \"morning\": [\n        \"Breakfast at Caffè Granja Viader\",\n        \"Visit Park Güell\",\n        \"Explore the trendy El Born neighborhood\"\n      ],\n      \"afternoon\": [\n        \"Lunch at Cal Pep\",\n        \"Visit the Joan Miro Museum\",\n        \"Beach time at Barceloneta\"\n      ],\n      \"evening\": [\n        \"Dinner at Tickets Bar\",\n        \"Enjoy a cocktail at a rooftop bar with views of the city\",\n        \"Live music at a local jazz club\"\n      ]\n    },\n    {\n      \"day\": 3,\n      \"morning\": [\n        \"Breakfast at a local bakery\",\n        \"Visit the Barcelona Cathedral\",\n        \"Shopping for souvenirs on Passeig de Gracia\"\n      ],\n      \"afternoon\": [\n        \"Lunch at La Pubilla\",\n        \"Visit the Montjuïc Hill and enjoy the views of the city\",\n        \"Departure\"\n      ],\n      \"evening\": []\n    }\n  ],\n  \"budget_estimate\": {\n    \"flight_from_Germany\": 150,\n    \"hotel_total\": 400,\n    \"daily_expenses_total\": 250,\n    \"total_trip_cost\": 1050\n  }\n}\n```"
    },
    {
      "role": "user",
      "content": "I have 900€ budget.\nI want to travel for 3 days.\nDeparture: Germany.\n\nTravel style: Adventure and nature."
    },
    {
      "role": "assistant",
      "content": "```json\n{\n  \"destination\": \"Interlaken, Switzerland\",\n  \"country\": \"Switzerland\",\n  \"overview\": \"A picturesque town in the Swiss Alps, surrounded by mountains, lakes, and lush forests.\",\n  \"local_event_or_festival\": \"Unspunnenfest (every 3 years)\",\n  \"best_time_to_visit\": \"Summer (June-September) for warm weather and outdoor activities\",\n  \"itinerary\": [\n    {\n      \"day\": 1,\n      \"morning\": [\n        \"Hike to the top of Schilthorn Mountain\",\n        \"Enjoy breathtaking views of the Eiger, Mönch, and Jungfrau mountains\",\n        \"Paragliding or canyoning adventure\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a mountain restaurant\",\n        \"Take a scenic boat ride on Lake Thun or Lake Brienz\",\n        \"Visit the picturesque village of Unterseen\"\n      ],\n      \"evening\": [\n        \"Dinner at a traditional Swiss restaurant\",\n        \"Stargazing in the peaceful Alpine surroundings\"\n      ]\n    },\n    {\n      \"day\": 2,\n      \"morning\": [\n        \"Cable car ride to the top of Jungfraujoch\",\n        \"Explore the glacier and ice palace\",\n        \"Hike to the nearby Grindelwald valley\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a mountain hut\",\n        \"White-water rafting or kayaking on the Lütschine River\",\n        \"Visit a local farm and try Swiss cheese and chocolate\"\n      ],\n      \"evening\": [\n        \"Dinner at a cozy mountain lodge\",\n        \"Relax in a natural hot spring or sauna\"\n      ]\n    },\n    {\n      \"day\": 3,\n      \"morning\": [\n        \"Hike to the top of Hasliberg Mountain\",\n        \"Enjoy panoramic views of the surrounding mountains and lakes\",\n        \"Zip line or canyoning adventure\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a local restaurant\",\n        \"Return to Interlaken and visit the Höheweg, a scenic hiking trail\",\n        \"Departure\"\n      ],\n      \"evening\": []\n    }\n  ],\n  \"budget_estimate\": {\n    \"flight_from_Germany\": 200,\n    \"hotel_total\": 300,\n    \"daily_expenses_total\": 150,\n    \"total_trip_cost\": 650\n  }\n}\n```"
    },
    {
      "role": "user",
      "content": "Estimate total cost for a 3-day trip to Vienna from Germany.\nHotel type: 4-star\nTravel style: Romantic.\n\n"
    },
    {
      "role": "assistant",
      "content": "```json\n{\n  \"destination\": \"Vienna, Austria\",\n  \"country\": \"Austria\",\n  \"overview\": \"A city of grandeur, music, and romance, famous for its imperial palaces, opera houses, and charming coffee culture.\",\n  \"local_event_or_festival\": \"Vienna Opera Ball (February-March)\",\n  \"best_time_to_visit\": \"Spring (April-May) and Autumn (September-October) for pleasant weather\",\n  \"itinerary\": [\n    {\n      \"day\": 1,\n      \"morning\": [\n        \"Breakfast at Café Central\",\n        \"Visit Schönbrunn Palace\",\n        \"Stroll through the gardens\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a traditional Viennese restaurant\",\n        \"Visit St. Stephen's Cathedral\",\n        \"Explore the charming streets of the Innere Stadt\"\n      ],\n      \"evening\": [\n        \"Dinner at a Michelin-starred restaurant\",\n        \"Enjoy a Mozart concert at the Musikverein\",\n        \"Horse-drawn carriage ride through the city\"\n      ]\n    },\n    {\n      \"day\": 2,\n      \"morning\": [\n        \"Breakfast at a local bakery\",\n        \"Visit the Hofburg Palace\",\n        \"Explore the Spanish Riding School\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a traditional Viennese coffeehouse\",\n        \"Visit the Belvedere Palace\",\n        \"Stroll through the Prater park\"\n      ],\n      \"evening\": [\n        \"Dinner at a cozy restaurant\",\n        \"Enjoy a performance at the Vienna State Opera\",\n        \"Evening stroll along the Ringstrasse\"\n      ]\n    },\n    {\n      \"day\": 3,\n      \"morning\": [\n        \"Breakfast at a café\",\n        \"Visit the Naschmarkt market\",\n        \"Shopping for souvenirs\"\n      ],\n      \"afternoon\": [\n        \"Lunch at a local restaurant\",\n        \"Departure\"\n      ],\n      \"evening\": []\n    }\n  ],\n  \"budget_estimate\": {\n    \"flight_from_Germany\": 150,\n    \"hotel_total\": 500,\n    \"daily_expenses_total\": 250,\n    \"total_trip_cost\": 900\n  }\n}\n```"
    },
    {
      "role": "user",
      "content": ""
    }
  ],
  "model": "meta-llama/llama-4-scout-17b-16e-instruct",
  "temperature": 0.3,
  "max_completion_tokens": 1024,
  "top_p": 1,
  "stream": true,
  "stop": null
});

for await (const chunk of chatCompletion) {
  process.stdout.write(chunk.choices[0]?.delta?.content || '');
}

