export const locationSuggestions = [
  "Prishtina, Kosovo",
  "Prizren, Kosovo",
  "Peja, Kosovo",
  "Tirana, Albania",
  "Saranda, Albania",
  "Shkoder, Albania",
  "Skopje, North Macedonia",
  "Ohrid, North Macedonia",
  "Podgorica, Montenegro",
  "Budva, Montenegro",
  "Dubrovnik, Croatia",
  "Split, Croatia",
  "Zagreb, Croatia",
  "Belgrade, Serbia",
  "Sarajevo, Bosnia and Herzegovina",
  "Mostar, Bosnia and Herzegovina",
  "Ljubljana, Slovenia",
  "Lake Bled, Slovenia",
  "Athens, Greece",
  "Santorini, Greece",
  "Mykonos, Greece",
  "Thessaloniki, Greece",
  "Rome, Italy",
  "Milan, Italy",
  "Venice, Italy",
  "Florence, Italy",
  "Naples, Italy",
  "Paris, France",
  "Nice, France",
  "Lyon, France",
  "Barcelona, Spain",
  "Madrid, Spain",
  "Seville, Spain",
  "Valencia, Spain",
  "Lisbon, Portugal",
  "Porto, Portugal",
  "London, United Kingdom",
  "Manchester, United Kingdom",
  "Edinburgh, United Kingdom",
  "Dublin, Ireland",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "Brussels, Belgium",
  "Berlin, Germany",
  "Munich, Germany",
  "Hamburg, Germany",
  "Vienna, Austria",
  "Salzburg, Austria",
  "Prague, Czech Republic",
  "Budapest, Hungary",
  "Warsaw, Poland",
  "Krakow, Poland",
  "Bucharest, Romania",
  "Cluj-Napoca, Romania",
  "Sofia, Bulgaria",
  "Istanbul, Turkey",
  "Antalya, Turkey",
  "Cappadocia, Turkey",
  "Dubai, United Arab Emirates",
  "Abu Dhabi, United Arab Emirates",
  "Doha, Qatar",
  "Cairo, Egypt",
  "Marrakesh, Morocco",
  "Cape Town, South Africa",
  "Nairobi, Kenya",
  "New York, United States",
  "Los Angeles, United States",
  "Chicago, United States",
  "Miami, United States",
  "San Francisco, United States",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Mexico City, Mexico",
  "Cancun, Mexico",
  "Rio de Janeiro, Brazil",
  "Sao Paulo, Brazil",
  "Buenos Aires, Argentina",
  "Lima, Peru",
  "Bogota, Colombia",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Kyoto, Japan",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Bangkok, Thailand",
  "Phuket, Thailand",
  "Chiang Mai, Thailand",
  "Bali, Indonesia",
  "Jakarta, Indonesia",
  "Singapore",
  "Kuala Lumpur, Malaysia",
  "Maldives",
  "Colombo, Sri Lanka",
  "Delhi, India",
  "Mumbai, India",
  "Goa, India",
  "Kathmandu, Nepal",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Auckland, New Zealand",
  "Iceland",
  "Norway",
  "Switzerland",
  "Austria",
  "France",
  "Italy",
  "Spain",
  "Portugal",
  "Germany",
  "Netherlands",
  "Belgium",
  "United Kingdom",
  "Ireland",
  "Croatia",
  "Greece",
  "Turkey",
  "Albania",
  "Kosovo",
  "North Macedonia",
  "Montenegro",
  "Bosnia and Herzegovina",
  "Slovenia",
  "Romania",
  "Bulgaria",
  "Poland",
  "Hungary",
  "Czech Republic",
  "Japan",
  "South Korea",
  "Thailand",
  "Indonesia",
  "Malaysia",
  "Singapore",
  "India",
  "United Arab Emirates",
  "Qatar",
  "Egypt",
  "Morocco",
  "South Africa",
  "United States",
  "Canada",
  "Mexico",
  "Brazil",
  "Argentina",
  "Peru",
  "Colombia",
  "Australia",
  "New Zealand"
];

export const normalizedLocations = [...new Set(locationSuggestions)].sort((a, b) =>
  a.localeCompare(b)
);
